projects: *projects
  target: auto
  threshold: 10%
  if_not_found: success
  if_ci_failed: error
patch: *patch
  only_pulls: true
  target: auto
  threshold: 10%

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default: off
      linux-1.13:
        <<: *projects
      linux-1.14:
        <<: *projects
      linux-1.15:
        <<: *projects
      macos-1.13:
        <<: *projects
      macos-1.14:
        <<: *projects
      macos-1.15:
        <<: *projects
    patch:
      default: off
      linux-1.13:
        <<: *patch
      linux-1.14:
        <<: *patch
      linux-1.15:
        <<: *patch
      macos-1.13:
        <<: *patch
      macos-1.14:
        <<: *patch
      macos-1.15:
        <<: *patch
    changes: true

flags:
  linux-1.13:
    paths:
      - /
    carryforward: true
  linux-1.14:
    paths:
      - /
    carryforward: true
  linux-1.15:
    paths:
      - /
    carryforward: true
  macos-1.13:
    paths:
      - /
    carryforward: true
  macos-1.14:
    paths:
      - /
    carryforward: true
  macos-1.15:
    paths:
      - /
    carryforward: true

comment:
  behavior: default
  require_changes: true
