projects: *projects
  target: auto
  threshold: 10%
  if_not_found: success
  if_ci_failed: error
patch: *patch
  only_pulls: true
  target: auto
  threshold: 10%

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default: off
      Linux-1.13.x:
        <<: *projects
      Linux-1.14.x:
        <<: *projects
      Linux-1.15.x:
        <<: *projects
      macOS-1.13.x:
        <<: *projects
      macOS-1.14.x:
        <<: *projects
      macOS-1.15.x:
        <<: *projects
    patch:
      default: off
      Linux-1.13.x:
        <<: *patch
      Linux-1.14.x:
        <<: *patch
      Linux-1.15.x:
        <<: *patch
      macOS-1.13.x:
        <<: *patch
      macOS-1.14.x:
        <<: *patch
      macOS-1.15.x:
        <<: *patch
    changes: true

flags:
  Linux-1.13.x:
    paths:
      - /
    carryforward: true
  Linux-1.14.x:
    paths:
      - /
    carryforward: true
  Linux-1.15.x:
    paths:
      - /
    carryforward: true
  macOS-1.13.x:
    paths:
      - /
    carryforward: true
  macOS-1.14.x:
    paths:
      - /
    carryforward: true
  macOS-1.15.x:
    paths:
      - /
    carryforward: true

comment:
  behavior: default
  require_changes: true
