codecov:
  allow_coverage_offsets: true

parsers:
  go:
    partials_as_hits: true

coverage:
  precision: 1
  range: "70...100"
  round: down

  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: include

    project:
      default: false
      linux-1.15-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - linux-1.15-stable
      linux-1.15-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - linux-1.15-nightly
      linux-1.16-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - linux-1.16-stable
      linux-1.16-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - linux-1.16-nightly
      linux-1.17-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - linux-1.17-stable
      linux-1.17-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - linux-1.17-nightly
      macos-1.15-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - macos-1.15-stable
      macos-1.15-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - macos-1.15-nightly
      macos-1.16-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - macos-1.16-stable
      macos-1.16-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - macos-1.16-nightly
      macos-1.17-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - macos-1.17-stable
      macos-1.17-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - macos-1.17-nightly
      windows-1.15-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - windows-1.15-stable
      windows-1.15-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - windows-1.15-nightly
      windows-1.16-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - windows-1.16-stable
      windows-1.16-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - windows-1.16-nightly
      windows-1.17-stable:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - windows-1.17-stable
      windows-1.17-nightly:
        target: auto
        threshold: 1.0
        if_not_found: success
        flags:
          - windows-1.17-nightly

    patch:
      default: false
      linux-1.15-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      linux-1.15-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      linux-1.16-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      linux-1.16-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      linux-1.17-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      linux-1.17-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      macos-1.15-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      macos-1.15-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      macos-1.16-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      macos-1.16-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      macos-1.17-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      macos-1.17-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      windows-1.15-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      windows-1.15-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      windows-1.16-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      windows-1.16-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      windows-1.17-stable:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure
      windows-1.17-nightly:
        target: auto
        threshold: 10.0
        only_pulls: true
        if_not_found: failure

    changes:
      default:
        if_not_found: success
        only_pulls: false
        branches:
          - master
        flags:
          - "linux-1.15-stable"
          - "linux-1.15-nightly"
          - "linux-1.16-stable"
          - "linux-1.16-nightly"
          - "linux-1.17-stable"
          - "linux-1.17-nightly"
          - "macos-1.15-stable"
          - "macos-1.15-nightly"
          - "macos-1.16-stable"
          - "macos-1.16-nightly"
          - "macos-1.17-stable"
          - "macos-1.17-nightly"
          - "windows-1.15-stable"
          - "windows-1.15-nightly"
          - "windows-1.16-stable"
          - "windows-1.16-nightly"
          - "windows-1.17-stable"
          - "windows-1.17-nightly"

flags:
  linux-1.15-nightly:
    carryforward: true
    paths:
      - /
  linux-1.15-stable:
    carryforward: true
    paths:
      - /
  linux-1.16-nightly:
    carryforward: true
    paths:
      - /
  linux-1.16-stable:
    carryforward: true
    paths:
      - /
  linux-1.17-nightly:
    carryforward: true
    paths:
      - /
  linux-1.17-stable:
    carryforward: true
    paths:
      - /
  macos-1.15-nightly:
    carryforward: true
    paths:
      - /
  macos-1.15-stable:
    carryforward: true
    paths:
      - /
  macos-1.16-nightly:
    carryforward: true
    paths:
      - /
  macos-1.16-stable:
    carryforward: true
    paths:
      - /
  macos-1.17-nightly:
    carryforward: true
    paths:
      - /
  macos-1.17-stable:
    carryforward: true
    paths:
      - /
  windows-1.15-nightly:
    carryforward: true
    paths:
      - /
  windows-1.15-stable:
    carryforward: true
    paths:
      - /
  windows-1.16-nightly:
    carryforward: true
    paths:
      - /
  windows-1.16-stable:
    carryforward: true
    paths:
      - /
  windows-1.17-nightly:
    carryforward: true
    paths:
      - /
  windows-1.17-stable:
    carryforward: true
    paths:
      - /

comment:
  behavior: default
  require_changes: true

github_checks:
  annotations: true
